### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nichtemna** [flavienlaurent/sandbox#1]
Got a crash on android os 10, a lot of crashes on every screen.
What the min sdk for this beauty?

**Comment by nichtemna** [comment]
12-05 09:34:03.163: ERROR/ResourceType(5286): Style contains key with bad entry: 0x010102e4
12-05 09:34:03.253: ERROR/AndroidRuntime(5286): FATAL EXCEPTION: main
        java.lang.NoSuchMethodError: com.fourmob.sandbox.activities.FadingABHeaderSmoothScrollActivity.getActionBar
        at com.fourmob.sandbox.activities.FadingABHeaderSmoothScrollActivity.updateActionBarAlpha(FadingABHeaderSmoothScrollActivity.java:95)
        at com.fourmob.sandbox.activities.FadingABHeaderSmoothScrollActivity.access$100(FadingABHeaderSmoothScrollActivity.java:21)
        at com.fourmob.sandbox.activities.FadingABHeaderSmoothScrollActivity$2.onScroll(FadingABHeaderSmoothScrollActivity.java:83)
        at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:791)
        at android.widget.AbsListView.setOnScrollListener(AbsListView.java:780)
        at com.fourmob.sandbox.activities.FadingABHeaderSmoothScrollActivity.onCreate(FadingABHeaderSmoothScrollActivity.java:73)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1072)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1836)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1893)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1054)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:4389)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
        at dalvik.system.NativeStart.main(Native Method)
12-05 09:34:03.263: ERROR/EmbeddedLogger(183): App crashed! Process: com.fourmob.sandbox
12-05 09:34:03.263: ERROR/EmbeddedLogger(183): App crashed! Package: com.fourmob.sandbox v1 (1.0)
12-05 09:34:03.263: ERROR/EmbeddedLogger(183): Error getting package label: com.fourmob.sandbox
        java.lang.NullPointerException
        at com.htc.server.embedded.EmbeddedLogger.onHandleApplicationCrash(EmbeddedLogger.java:59)
        at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:7739)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1033)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:1657)
        at android.os.Binder.execTransact(Binder.java:320)
        at dalvik.system.NativeStart.run(Native Method)
12-05 09:34:03.263: ERROR/EmbeddedLogger(183): Application Label: <ERROR>

**Comment by flavienlaurent** [comment]
http://developer.android.com/reference/android/app/Activity.html#getActionBar()
